Models/Book.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models
{
    public class Book
    {
        [Key]
        public int ID { get; set; }
        public string ISBN { get; set; }
        public string Title { get; set; }
        public decimal Price { get; set; }
    }
}

Models/Customer.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models
{
    public class Customer
    {
        [Key]
        public int ID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WebApp.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService book;
        public BookController(IBookService _book){
            book = _book;
        }
        public async Task<IActionResult> Index(string txt)
        {
            ViewBag.Txt = txt;
            return View(await book.SearchTxt(txt));
        }
        public IActionResult Add(){
            return View();
        }
        [HttpPost]
        public IActionResult NewData(Book b){
            book.NewData(b);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id){
            if(book.Edit(id)){
                var add = book.EditData(id);
                return View(add);
            }
            return View("Index");
        }
        [HttpPost]
        public IActionResult BookEdit(Book mbook){
            if(book.Edit(mbook.ID)) book.BookEdit(mbook);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult DeleteBook(int id){
            if(book.Edit(id)) book.RemoveBook(id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAuthService auth;

        public HomeController(IAuthService _auth)
        {
            auth = _auth;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Auth([FromBody]Customer customer)
        {
            if(auth.Auth(customer)) return Json(new {code = 200,token = customer.username});
            return Json(new {code = 400});
        }
    }
}

Views/Book/Add.cshtml
@{
ViewData["Title"] = "Book Add";
}

@using (Html.BeginForm("NewData", "Book", FormMethod.Post))
{
<div class="mr-auto mb-auto ml-auto mt-5 border pr-5 pl-5 pt-5 pb-3 rounded shadow" style="width: 600px;">
    <div class="row">
        <div class="col-12 mb-4"><input name="ISBN" type="text" class="form-control" placeholder="รหัส" autocomplete="off" required></div>
        <div class="col-12 mb-4"><input name="Title" type="text" class="form-control" placeholder="ชื่อ" autocomplete="off" required></div>
        <div class="col-12 mb-5"><input name="Price" type="number" step="any" class="form-control" placeholder="ราคา" autocomplete="off" required></div>
    </div>
    <div class="d-flex justify-content-end">
        <a asp-controller="Book" asp-action="Index" class="btn btn-danger mr-3">ยกเลิก</a>
        <button type="submit" class="btn btn-warning">เพิ่มหนังสือ</button>
    </div>
</div>
}

Views/Book/Edit.cshtml
@model WebApp.Models.Book
@{
ViewData["Title"] = "Book Edit";
}

@using (Html.BeginForm("BookEdit", "Book", new {ID = Model.ID}, FormMethod.Post))
{
<div class="mr-auto mb-auto ml-auto mt-5 border pr-5 pl-5 pt-5 pb-3 rounded shadow" style="width: 600px;">
    <div class="row">
        <div class="col-12 mb-4"><input name="ISBN" autocomplete="off" required type="text" value="@Model.ISBN"
                class="form-control" placeholder="รหัส"></div>
        <div class="col-12 mb-4"><input name="Title" autocomplete="off" required type="text" value="@Model.Title"
                class="form-control" placeholder="ชื่อ"></div>
        <div class="col-12 mb-5"><input name="Price" autocomplete="off" required type="number" step="any" value="@Model.Price"
                class="form-control" placeholder="ราคา"></div>
    </div>
    <div class="d-flex justify-content-end">
        <a asp-controller="Book" asp-action="Index" class="btn btn-danger mr-3">ยกเลิก</a>
        <button type="submit" class="btn btn-warning">อัพเดตข้อมูลหนังสือ</button>
    </div>
</div>
}

Views/Book/Index.cshtml
@model IEnumerable<WebApp.Models.Book>
@{
    ViewData["Title"] = "Book List";
}
<div class="row mb-4 mt-4">
    <div class="col-7 d-inline align-items-center">
    @using (Html.BeginForm("Index", "Book", FormMethod.Get)){
        <input name="txt" value="@ViewBag.Txt" type="text" class="form-control d-inline col-9" autocomplete="off" placeholder="ค้นหาหนังสือ">
    }
    </div>
    <div class="col-5 d-flex justify-content-end"><a class="btn btn-success" asp-area="" asp-controller="Book" asp-action="Add">เพิ่มข้อมูล</a></div>
</div>
<table class="table table-striped table-bordered table-hover text-center">
    <thead>
        <tr>
            <th>รหัส</th>
            <th>ชื่อ</th>
            <th>ราคา</th>
            <th>จัดการ</th>
        </tr>
    </thead>
    <tbody>
        @if(Model.Count() != 0){
            foreach(var item in Model){
                <tr>
                    <td>@item.ISBN</td>
                    <td>@item.Title</td>
                    <td>@string.Format($"{@item.Price:n}")</td>
                    <td><a href="/Book/Edit/@(item.ID)" class="btn btn-warning btn-sm mr-1">แก้ไข</a>
                        |<a href="/Book/DeleteBook/@(item.ID)" class="btn btn-danger btn-sm ml-1">ลบ</a></td>
                </tr>
            }
        }else{
            <tr>
                <td class="h4" colspan="4">ไม่พบข้อมูล</td>
            </tr>
        }
    </tbody>
</table>
@section scripts {
    <!--จะแสดงใต้ RenderSection ของหน้าเว็บนี้เท่านั้น -->
     <!--<script src="~/js/out.js"></script> -->
}

Views/Home/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css2?family=Sarabun&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/login.css" />
</head>
<body style="font-family: 'Sarabun', sans-serif;">
        <div class="card login p-4">
            <h3 class="text-center">เข้าสู่ระบบ</h3>
            <div class="row">
                <div class="col-12 pt-4 pr-4 pl-4">
                    <input id="username" name="username" class="form-control" type="text" placeholder="ชื่อผู้ใช้งาน" autocomplete="off" required />
                </div>
                <div class="col-12 pt-4 pr-4 pl-4">
                    <input id="password" name="password" class="form-control" type="password" placeholder="รหัสผ่าน" autocomplete="off" required />
                </div>
            </div>
            <div class="d-flex justify-content-center pt-4">
                <button class="btn btn-success" id="Auth">เข้าสู่ระบบ</button>
            </div>
        </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/auth.js" asp-append-version="true"></script>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css2?family=Sarabun&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="font-family: 'Sarabun', sans-serif;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Book" asp-action="Index">ร้านหนังสือ</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li class="nav-item">
                            <button class="btn btn-outline-danger btn-sm" id="logout">ออกจากระบบ</button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; WebApp(Demo) - suchujkaenasa@gmail.com
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>